server:
  port: 8080 
  servlet:
    context-path: / 
    encoding:
      charset: UTF-8
      enabled: true
      force: true
     
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/roomescape?serverTimezone=Asia/Seoul
    username: roomescape
    password: room1234


       

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp   
      
  

  security:
    oauth2:
      client:
        registration:
         google: #/oauth2/authorization/google이 주소를 동작하게 한다.
            client-id: 498616760088-n6kden8grq013su83v829jaqm4sip6kc.apps.googleusercontent.com
            client-secret: VHRhFfV3sGOpGXeUL79n3Uf5
            scope:
            - email
            - profile
      
      
         facebook: #/oauth2/authorization/facebook이 주소를 동작하게 한다.
           client-id: 757772171716943
           client-secret: 17fe7387f4b26fe7ec6980660166ac50 
           scope:
        
        
          # 네이버는 OAuth2.0 공식 지원대상이 아니라서 provider 설정이 필요하다.
          # 요청주소도 다르고, 응답 데이터도 다르기 때문이다.
          
         naver:
           client-id: wxSu3dDOudxgr89lOpwT
           client-secret: QfWAABtrre            
           scope:            - name
            - email
            - profile_image  
           client-name: Naver 
           authorization-grant-type: authorization_code
           redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:          naver:
           authorization-uri: https://nid.naver.com/oauth2.0/authorize
           token-uri: https://nid.naver.com/oauth2.0/token
           user-info-uri: https://openapi.naver.com/v1/nid/me
           user-name-attribute: response # 회원정보를 json의 response 키값으로 리턴해줌.             
              
                 