server:
  port: 8080 
  servlet:
    context-path: / 
    encoding:
      charset: UTF-8
      enabled: true
      force: true
     
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/roomescape?serverTimeZone=Asia/Seoul
    username: roomescape
    password: room1234

       
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .mustache
      
  security:
    oauth2:
      client:
        registration:
         google: #/oauth2/authorization/google이 주소를 동작하게 한다.
            client-id: 498616760088-n6kden8grq013su83v829jaqm4sip6kc.apps.googleusercontent.com
            client-secret: VHRhFfV3sGOpGXeUL79n3Uf5
            scope:
            - email
            - profile
      
      
        # facebook: #/oauth2/authorization/facebook이 주소를 동작하게 한다.
         #  client-id: 
          # client-secret: 
          # scope:
            - email
            - profile           
              
                 